### ISSUE TITLE
RightOn Mobile UI: Phase 1 Submit Answer

### ISSUE THREAD

**Issue by lucahendicott** [rightoneducation/righton-app#380]
Currently the answer options themselves are the buttons for submitting. 

[Source Code](https://github.com/rightoneducation/righton-app/tree/dev/mobile/src/Student/screens/Game/PhaseOneBasicGamePlay)

**ToDo:**
- [x] Add submit button below answer options and rework functionality for submitting the answer selection once that bad boy is pressed!
- [x] Update border color of answer options
- [x] Update the dot on the right side of the answer option button (currently a green checkmark - need blue dot)
- [x] Add " Thank you for submitting" blurb once the answer is submitted
- [x] Remove green score from footer

![Image](https://user-images.githubusercontent.com/70814349/198129260-0c8dcc3e-cf7e-4fa7-9788-fd4f621d7fa3.png)
